name: CI

on: [push, pull_request]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v5

  ci-checks:
    needs: spell-check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        uv-version: ["0.7.14"]
        ruff-target-version: ["py39"]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ matrix.uv-version }}
      - name: Install dependencies
        shell: bash
        run: uv sync --group dev

      - name: Validating format with Ruff
        run: |
          uv run ruff format --check --quiet --diff --target-version ${{ matrix.ruff-target-version }}
      - name: Linting with Ruff
        run: |
          uv run ruff check --target-version ${{ matrix.ruff-target-version }} --output-format=github .
      - name: Checking imports with isort
        run: |
          uv run isort -c --profile black --python-version auto .
      - name: Checking formatting with black
        run: |
          uv run black --check .
      - name: Checking style with flake8
        run: |
          uv run flake8 .
      - name: Analysing the code with pylint
        run: |
          uv run pylint $(git ls-files '*.py')
      - name: Analyzing typing with pyright
        run: |
          uv run pyright --pythonversion ${{ matrix.python-version }}
      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: false
          job-summary: true
          custom-pytest: "uv run pytest"
          custom-arguments: "-q"
          click-to-expand: true
          report-title: "Test Report"
